// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(celestia_grpcFFI)
import celestia_grpcFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_celestia_grpc_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_celestia_grpc_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureCelestiaGrpcInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * Celestia GRPC client
 */
public protocol GrpcClientProtocol: AnyObject, Sendable {
    
    /**
     * Broadcast prepared and serialised transaction
     */
    func broadcastTx(txBytes: Data, mode: BroadcastMode) async throws  -> TxResponse
    
    /**
     * Get account
     */
    func getAccount(account: RustAddress) async throws  -> Account
    
    /**
     * Get accounts
     */
    func getAccounts() async throws  -> [Account]
    
    /**
     * Get balance of all coins
     */
    func getAllBalances(address: RustAddress) async throws  -> [Coin]
    
    /**
     * Get auth params
     */
    func getAuthParams() async throws  -> Params
    
    /**
     * Get balance of coins with given denom
     */
    func getBalance(address: RustAddress, denom: String) async throws  -> Coin
    
    /**
     * Get blob params
     */
    func getBlobParams() async throws  -> BlobParams
    
    /**
     * Get block by height
     */
    func getBlockByHeight(height: Int64) async throws  -> Block
    
    /**
     * Get latest block
     */
    func getLatestBlock() async throws  -> Block
    
    /**
     * Get Minimum Gas price
     */
    func getMinGasPrice() async throws  -> Double
    
    /**
     * Get balance of all spendable coins
     */
    func getSpendableBalances(address: RustAddress) async throws  -> [Coin]
    
    /**
     * Get total supply
     */
    func getTotalSupply() async throws  -> [Coin]
    
    /**
     * Get Tx
     */
    func getTx(hash: UniffiHash) async throws  -> GetTxResponse
    
    /**
     * Broadcast prepared and serialised transaction
     */
    func simulate(txBytes: Data) async throws  -> GasInfo
    
    /**
     * Get status of the transaction
     */
    func txStatus(hash: UniffiHash) async throws  -> TxStatusResponse
    
}
/**
 * Celestia GRPC client
 */
open class GrpcClient: GrpcClientProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_celestia_grpc_fn_clone_grpcclient(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_celestia_grpc_fn_free_grpcclient(pointer, $0) }
    }

    
    /**
     * Create a new client connected with the given `url`
     */
public static func create(url: String)async throws  -> GrpcClient  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_celestia_grpc_fn_constructor_grpcclient_create(FfiConverterString.lower(url)
                )
            },
            pollFunc: ffi_celestia_grpc_rust_future_poll_pointer,
            completeFunc: ffi_celestia_grpc_rust_future_complete_pointer,
            freeFunc: ffi_celestia_grpc_rust_future_free_pointer,
            liftFunc: FfiConverterTypeGrpcClient_lift,
            errorHandler: FfiConverterTypeGrpcClientError_lift
        )
}
    

    
    /**
     * Broadcast prepared and serialised transaction
     */
open func broadcastTx(txBytes: Data, mode: BroadcastMode)async throws  -> TxResponse  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_celestia_grpc_fn_method_grpcclient_broadcast_tx(
                    self.uniffiClonePointer(),
                    FfiConverterData.lower(txBytes),FfiConverterTypeBroadcastMode_lower(mode)
                )
            },
            pollFunc: ffi_celestia_grpc_rust_future_poll_rust_buffer,
            completeFunc: ffi_celestia_grpc_rust_future_complete_rust_buffer,
            freeFunc: ffi_celestia_grpc_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeTxResponse_lift,
            errorHandler: FfiConverterTypeGrpcClientError_lift
        )
}
    
    /**
     * Get account
     */
open func getAccount(account: RustAddress)async throws  -> Account  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_celestia_grpc_fn_method_grpcclient_get_account(
                    self.uniffiClonePointer(),
                    FfiConverterTypeRustAddress_lower(account)
                )
            },
            pollFunc: ffi_celestia_grpc_rust_future_poll_rust_buffer,
            completeFunc: ffi_celestia_grpc_rust_future_complete_rust_buffer,
            freeFunc: ffi_celestia_grpc_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeAccount_lift,
            errorHandler: FfiConverterTypeGrpcClientError_lift
        )
}
    
    /**
     * Get accounts
     */
open func getAccounts()async throws  -> [Account]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_celestia_grpc_fn_method_grpcclient_get_accounts(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_celestia_grpc_rust_future_poll_rust_buffer,
            completeFunc: ffi_celestia_grpc_rust_future_complete_rust_buffer,
            freeFunc: ffi_celestia_grpc_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeAccount.lift,
            errorHandler: FfiConverterTypeGrpcClientError_lift
        )
}
    
    /**
     * Get balance of all coins
     */
open func getAllBalances(address: RustAddress)async throws  -> [Coin]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_celestia_grpc_fn_method_grpcclient_get_all_balances(
                    self.uniffiClonePointer(),
                    FfiConverterTypeRustAddress_lower(address)
                )
            },
            pollFunc: ffi_celestia_grpc_rust_future_poll_rust_buffer,
            completeFunc: ffi_celestia_grpc_rust_future_complete_rust_buffer,
            freeFunc: ffi_celestia_grpc_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeCoin.lift,
            errorHandler: FfiConverterTypeGrpcClientError_lift
        )
}
    
    /**
     * Get auth params
     */
open func getAuthParams()async throws  -> Params  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_celestia_grpc_fn_method_grpcclient_get_auth_params(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_celestia_grpc_rust_future_poll_rust_buffer,
            completeFunc: ffi_celestia_grpc_rust_future_complete_rust_buffer,
            freeFunc: ffi_celestia_grpc_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeParams_lift,
            errorHandler: FfiConverterTypeGrpcClientError_lift
        )
}
    
    /**
     * Get balance of coins with given denom
     */
open func getBalance(address: RustAddress, denom: String)async throws  -> Coin  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_celestia_grpc_fn_method_grpcclient_get_balance(
                    self.uniffiClonePointer(),
                    FfiConverterTypeRustAddress_lower(address),FfiConverterString.lower(denom)
                )
            },
            pollFunc: ffi_celestia_grpc_rust_future_poll_rust_buffer,
            completeFunc: ffi_celestia_grpc_rust_future_complete_rust_buffer,
            freeFunc: ffi_celestia_grpc_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeCoin_lift,
            errorHandler: FfiConverterTypeGrpcClientError_lift
        )
}
    
    /**
     * Get blob params
     */
open func getBlobParams()async throws  -> BlobParams  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_celestia_grpc_fn_method_grpcclient_get_blob_params(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_celestia_grpc_rust_future_poll_rust_buffer,
            completeFunc: ffi_celestia_grpc_rust_future_complete_rust_buffer,
            freeFunc: ffi_celestia_grpc_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeBlobParams_lift,
            errorHandler: FfiConverterTypeGrpcClientError_lift
        )
}
    
    /**
     * Get block by height
     */
open func getBlockByHeight(height: Int64)async throws  -> Block  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_celestia_grpc_fn_method_grpcclient_get_block_by_height(
                    self.uniffiClonePointer(),
                    FfiConverterInt64.lower(height)
                )
            },
            pollFunc: ffi_celestia_grpc_rust_future_poll_rust_buffer,
            completeFunc: ffi_celestia_grpc_rust_future_complete_rust_buffer,
            freeFunc: ffi_celestia_grpc_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeBlock_lift,
            errorHandler: FfiConverterTypeGrpcClientError_lift
        )
}
    
    /**
     * Get latest block
     */
open func getLatestBlock()async throws  -> Block  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_celestia_grpc_fn_method_grpcclient_get_latest_block(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_celestia_grpc_rust_future_poll_rust_buffer,
            completeFunc: ffi_celestia_grpc_rust_future_complete_rust_buffer,
            freeFunc: ffi_celestia_grpc_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeBlock_lift,
            errorHandler: FfiConverterTypeGrpcClientError_lift
        )
}
    
    /**
     * Get Minimum Gas price
     */
open func getMinGasPrice()async throws  -> Double  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_celestia_grpc_fn_method_grpcclient_get_min_gas_price(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_celestia_grpc_rust_future_poll_f64,
            completeFunc: ffi_celestia_grpc_rust_future_complete_f64,
            freeFunc: ffi_celestia_grpc_rust_future_free_f64,
            liftFunc: FfiConverterDouble.lift,
            errorHandler: FfiConverterTypeGrpcClientError_lift
        )
}
    
    /**
     * Get balance of all spendable coins
     */
open func getSpendableBalances(address: RustAddress)async throws  -> [Coin]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_celestia_grpc_fn_method_grpcclient_get_spendable_balances(
                    self.uniffiClonePointer(),
                    FfiConverterTypeRustAddress_lower(address)
                )
            },
            pollFunc: ffi_celestia_grpc_rust_future_poll_rust_buffer,
            completeFunc: ffi_celestia_grpc_rust_future_complete_rust_buffer,
            freeFunc: ffi_celestia_grpc_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeCoin.lift,
            errorHandler: FfiConverterTypeGrpcClientError_lift
        )
}
    
    /**
     * Get total supply
     */
open func getTotalSupply()async throws  -> [Coin]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_celestia_grpc_fn_method_grpcclient_get_total_supply(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_celestia_grpc_rust_future_poll_rust_buffer,
            completeFunc: ffi_celestia_grpc_rust_future_complete_rust_buffer,
            freeFunc: ffi_celestia_grpc_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeCoin.lift,
            errorHandler: FfiConverterTypeGrpcClientError_lift
        )
}
    
    /**
     * Get Tx
     */
open func getTx(hash: UniffiHash)async throws  -> GetTxResponse  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_celestia_grpc_fn_method_grpcclient_get_tx(
                    self.uniffiClonePointer(),
                    FfiConverterTypeUniffiHash_lower(hash)
                )
            },
            pollFunc: ffi_celestia_grpc_rust_future_poll_rust_buffer,
            completeFunc: ffi_celestia_grpc_rust_future_complete_rust_buffer,
            freeFunc: ffi_celestia_grpc_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeGetTxResponse_lift,
            errorHandler: FfiConverterTypeGrpcClientError_lift
        )
}
    
    /**
     * Broadcast prepared and serialised transaction
     */
open func simulate(txBytes: Data)async throws  -> GasInfo  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_celestia_grpc_fn_method_grpcclient_simulate(
                    self.uniffiClonePointer(),
                    FfiConverterData.lower(txBytes)
                )
            },
            pollFunc: ffi_celestia_grpc_rust_future_poll_rust_buffer,
            completeFunc: ffi_celestia_grpc_rust_future_complete_rust_buffer,
            freeFunc: ffi_celestia_grpc_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeGasInfo_lift,
            errorHandler: FfiConverterTypeGrpcClientError_lift
        )
}
    
    /**
     * Get status of the transaction
     */
open func txStatus(hash: UniffiHash)async throws  -> TxStatusResponse  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_celestia_grpc_fn_method_grpcclient_tx_status(
                    self.uniffiClonePointer(),
                    FfiConverterTypeUniffiHash_lower(hash)
                )
            },
            pollFunc: ffi_celestia_grpc_rust_future_poll_rust_buffer,
            completeFunc: ffi_celestia_grpc_rust_future_complete_rust_buffer,
            freeFunc: ffi_celestia_grpc_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeTxStatusResponse_lift,
            errorHandler: FfiConverterTypeGrpcClientError_lift
        )
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGrpcClient: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = GrpcClient

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> GrpcClient {
        return GrpcClient(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: GrpcClient) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GrpcClient {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: GrpcClient, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGrpcClient_lift(_ pointer: UnsafeMutableRawPointer) throws -> GrpcClient {
    return try FfiConverterTypeGrpcClient.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGrpcClient_lower(_ value: GrpcClient) -> UnsafeMutableRawPointer {
    return FfiConverterTypeGrpcClient.lower(value)
}






/**
 * Celestia GRPC transaction client
 */
public protocol TxClientProtocol: AnyObject, Sendable {
    
    /**
     * AppVersion of the client
     */
    func appVersion()  -> AppVersion
    
    /**
     * Last gas price fetched by the client
     */
    func lastSeenGasPrice()  -> Double
    
    /**
     * Submit blobs to the celestia network.
     *
     * When no `TxConfig` is provided, client will automatically calculate needed
     * gas and update the `gasPrice`, if network agreed on a new minimal value.
     * To enforce specific values use a `TxConfig`.
     */
    func submitBlobs(blobs: [Blob], config: TxConfig?) async throws  -> TxInfo
    
    /**
     * Submit message to the celestia network.
     *
     * When no `TxConfig` is provided, client will automatically calculate needed
     * gas and update the `gasPrice`, if network agreed on a new minimal value.
     * To enforce specific values use a `TxConfig`.
     */
    func submitMessage(message: AnyMsg, config: TxConfig?) async throws  -> TxInfo
    
}
/**
 * Celestia GRPC transaction client
 */
open class TxClient: TxClientProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_celestia_grpc_fn_clone_txclient(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_celestia_grpc_fn_free_txclient(pointer, $0) }
    }

    
    /**
     * Create a new transaction client with the specified account.
     */
public static func create(url: String, accountAddress: RustAddress, accountPubkey: Data, signer: UniffiSigner)async throws  -> TxClient  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_celestia_grpc_fn_constructor_txclient_create(FfiConverterString.lower(url),FfiConverterTypeRustAddress_lower(accountAddress),FfiConverterData.lower(accountPubkey),FfiConverterTypeUniffiSigner_lower(signer)
                )
            },
            pollFunc: ffi_celestia_grpc_rust_future_poll_pointer,
            completeFunc: ffi_celestia_grpc_rust_future_complete_pointer,
            freeFunc: ffi_celestia_grpc_rust_future_free_pointer,
            liftFunc: FfiConverterTypeTxClient_lift,
            errorHandler: FfiConverterTypeTransactionClientError_lift
        )
}
    

    
    /**
     * AppVersion of the client
     */
open func appVersion() -> AppVersion  {
    return try!  FfiConverterTypeAppVersion_lift(try! rustCall() {
    uniffi_celestia_grpc_fn_method_txclient_app_version(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Last gas price fetched by the client
     */
open func lastSeenGasPrice() -> Double  {
    return try!  FfiConverterDouble.lift(try! rustCall() {
    uniffi_celestia_grpc_fn_method_txclient_last_seen_gas_price(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Submit blobs to the celestia network.
     *
     * When no `TxConfig` is provided, client will automatically calculate needed
     * gas and update the `gasPrice`, if network agreed on a new minimal value.
     * To enforce specific values use a `TxConfig`.
     */
open func submitBlobs(blobs: [Blob], config: TxConfig?)async throws  -> TxInfo  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_celestia_grpc_fn_method_txclient_submit_blobs(
                    self.uniffiClonePointer(),
                    FfiConverterSequenceTypeBlob.lower(blobs),FfiConverterOptionTypeTxConfig.lower(config)
                )
            },
            pollFunc: ffi_celestia_grpc_rust_future_poll_rust_buffer,
            completeFunc: ffi_celestia_grpc_rust_future_complete_rust_buffer,
            freeFunc: ffi_celestia_grpc_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeTxInfo_lift,
            errorHandler: FfiConverterTypeTransactionClientError_lift
        )
}
    
    /**
     * Submit message to the celestia network.
     *
     * When no `TxConfig` is provided, client will automatically calculate needed
     * gas and update the `gasPrice`, if network agreed on a new minimal value.
     * To enforce specific values use a `TxConfig`.
     */
open func submitMessage(message: AnyMsg, config: TxConfig?)async throws  -> TxInfo  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_celestia_grpc_fn_method_txclient_submit_message(
                    self.uniffiClonePointer(),
                    FfiConverterTypeAnyMsg_lower(message),FfiConverterOptionTypeTxConfig.lower(config)
                )
            },
            pollFunc: ffi_celestia_grpc_rust_future_poll_rust_buffer,
            completeFunc: ffi_celestia_grpc_rust_future_complete_rust_buffer,
            freeFunc: ffi_celestia_grpc_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeTxInfo_lift,
            errorHandler: FfiConverterTypeTransactionClientError_lift
        )
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTxClient: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = TxClient

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> TxClient {
        return TxClient(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: TxClient) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TxClient {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: TxClient, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTxClient_lift(_ pointer: UnsafeMutableRawPointer) throws -> TxClient {
    return try FfiConverterTypeTxClient.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTxClient_lower(_ value: TxClient) -> UnsafeMutableRawPointer {
    return FfiConverterTypeTxClient.lower(value)
}






/**
 * Trait that implements signing the transaction.
 *
 * Example usage:
 * ```swift
 * // uses 21-DOT-DEV/swift-secp256k1
 * final class StaticSigner : UniffiSigner {
 * let sk : P256K.Signing.PrivateKey
 *
 * init(sk: P256K.Signing.PrivateKey) {
 * self.sk = sk
 * }
 *
 * func sign(doc: SignDoc) async throws -> UniffiSignature {
 * let messageData = protoEncodeSignDoc(signDoc: doc);
 * let signature = try! sk.signature(for: messageData)
 * return try! UniffiSignature (bytes: signature.compactRepresentation)
 * }
 * }
 * ```
 */
public protocol UniffiSigner: AnyObject, Sendable {
    
    /**
     * sign provided `SignDoc` using secp256k1. Use helper proto_encode_sign_doc to
     * get canonical protobuf byte encoding of the message.
     */
    func sign(doc: SignDoc) async throws  -> UniffiSignature
    
}
/**
 * Trait that implements signing the transaction.
 *
 * Example usage:
 * ```swift
 * // uses 21-DOT-DEV/swift-secp256k1
 * final class StaticSigner : UniffiSigner {
 * let sk : P256K.Signing.PrivateKey
 *
 * init(sk: P256K.Signing.PrivateKey) {
 * self.sk = sk
 * }
 *
 * func sign(doc: SignDoc) async throws -> UniffiSignature {
 * let messageData = protoEncodeSignDoc(signDoc: doc);
 * let signature = try! sk.signature(for: messageData)
 * return try! UniffiSignature (bytes: signature.compactRepresentation)
 * }
 * }
 * ```
 */
open class UniffiSignerImpl: UniffiSigner, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_celestia_grpc_fn_clone_uniffisigner(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_celestia_grpc_fn_free_uniffisigner(pointer, $0) }
    }

    

    
    /**
     * sign provided `SignDoc` using secp256k1. Use helper proto_encode_sign_doc to
     * get canonical protobuf byte encoding of the message.
     */
open func sign(doc: SignDoc)async throws  -> UniffiSignature  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_celestia_grpc_fn_method_uniffisigner_sign(
                    self.uniffiClonePointer(),
                    FfiConverterTypeSignDoc_lower(doc)
                )
            },
            pollFunc: ffi_celestia_grpc_rust_future_poll_rust_buffer,
            completeFunc: ffi_celestia_grpc_rust_future_complete_rust_buffer,
            freeFunc: ffi_celestia_grpc_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeUniffiSignature_lift,
            errorHandler: FfiConverterTypeTransactionClientError_lift
        )
}
    

}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceUniffiSigner {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceUniffiSigner] = [UniffiVTableCallbackInterfaceUniffiSigner(
        sign: { (
            uniffiHandle: UInt64,
            doc: RustBuffer,
            uniffiFutureCallback: @escaping UniffiForeignFutureCompleteRustBuffer,
            uniffiCallbackData: UInt64,
            uniffiOutReturn: UnsafeMutablePointer<UniffiForeignFuture>
        ) in
            let makeCall = {
                () async throws -> UniffiSignature in
                guard let uniffiObj = try? FfiConverterTypeUniffiSigner.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try await uniffiObj.sign(
                     doc: try FfiConverterTypeSignDoc_lift(doc)
                )
            }

            let uniffiHandleSuccess = { (returnValue: UniffiSignature) in
                uniffiFutureCallback(
                    uniffiCallbackData,
                    UniffiForeignFutureStructRustBuffer(
                        returnValue: FfiConverterTypeUniffiSignature_lower(returnValue),
                        callStatus: RustCallStatus()
                    )
                )
            }
            let uniffiHandleError = { (statusCode, errorBuf) in
                uniffiFutureCallback(
                    uniffiCallbackData,
                    UniffiForeignFutureStructRustBuffer(
                        returnValue: RustBuffer.empty(),
                        callStatus: RustCallStatus(code: statusCode, errorBuf: errorBuf)
                    )
                )
            }
            let uniffiForeignFuture = uniffiTraitInterfaceCallAsyncWithError(
                makeCall: makeCall,
                handleSuccess: uniffiHandleSuccess,
                handleError: uniffiHandleError,
                lowerError: FfiConverterTypeTransactionClientError_lower
            )
            uniffiOutReturn.pointee = uniffiForeignFuture
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterTypeUniffiSigner.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface UniffiSigner: handle missing in uniffiFree")
            }
        }
    )]
}

private func uniffiCallbackInitUniffiSigner() {
    uniffi_celestia_grpc_fn_init_callback_vtable_uniffisigner(UniffiCallbackInterfaceUniffiSigner.vtable)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUniffiSigner: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<UniffiSigner>()

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = UniffiSigner

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> UniffiSigner {
        return UniffiSignerImpl(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: UniffiSigner) -> UnsafeMutableRawPointer {
        guard let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: handleMap.insert(obj: value))) else {
            fatalError("Cast to UnsafeMutableRawPointer failed")
        }
        return ptr
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UniffiSigner {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: UniffiSigner, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUniffiSigner_lift(_ pointer: UnsafeMutableRawPointer) throws -> UniffiSigner {
    return try FfiConverterTypeUniffiSigner.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUniffiSigner_lower(_ value: UniffiSigner) -> UnsafeMutableRawPointer {
    return FfiConverterTypeUniffiSigner.lower(value)
}




/**
 * Any contains an arbitrary serialized protocol buffer message along with a URL that
 * describes the type of the serialized message.
 */
public struct AnyMsg {
    /**
     * A URL/resource name that uniquely identifies the type of the serialized protocol
     * buffer message. This string must contain at least one “/” character. The last
     * segment of the URL’s path must represent the fully qualified name of the type
     * (as in path/google.protobuf.Duration). The name should be in a canonical form
     * (e.g., leading “.” is not accepted).
     */
    public var type: String
    /**
     * Must be a valid serialized protocol buffer of the above specified type.
     */
    public var value: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * A URL/resource name that uniquely identifies the type of the serialized protocol
         * buffer message. This string must contain at least one “/” character. The last
         * segment of the URL’s path must represent the fully qualified name of the type
         * (as in path/google.protobuf.Duration). The name should be in a canonical form
         * (e.g., leading “.” is not accepted).
         */type: String, 
        /**
         * Must be a valid serialized protocol buffer of the above specified type.
         */value: Data) {
        self.type = type
        self.value = value
    }
}

#if compiler(>=6)
extension AnyMsg: Sendable {}
#endif


extension AnyMsg: Equatable, Hashable {
    public static func ==(lhs: AnyMsg, rhs: AnyMsg) -> Bool {
        if lhs.type != rhs.type {
            return false
        }
        if lhs.value != rhs.value {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(type)
        hasher.combine(value)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAnyMsg: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AnyMsg {
        return
            try AnyMsg(
                type: FfiConverterString.read(from: &buf), 
                value: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: AnyMsg, into buf: inout [UInt8]) {
        FfiConverterString.write(value.type, into: &buf)
        FfiConverterData.write(value.value, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnyMsg_lift(_ buf: RustBuffer) throws -> AnyMsg {
    return try FfiConverterTypeAnyMsg.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnyMsg_lower(_ value: AnyMsg) -> RustBuffer {
    return FfiConverterTypeAnyMsg.lower(value)
}


/**
 * Response to GetTx
 */
public struct GetTxResponse {
    /**
     * Response Transaction
     */
    public var tx: Tx
    /**
     * TxResponse to a Query
     */
    public var txResponse: TxResponse

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Response Transaction
         */tx: Tx, 
        /**
         * TxResponse to a Query
         */txResponse: TxResponse) {
        self.tx = tx
        self.txResponse = txResponse
    }
}

#if compiler(>=6)
extension GetTxResponse: Sendable {}
#endif


extension GetTxResponse: Equatable, Hashable {
    public static func ==(lhs: GetTxResponse, rhs: GetTxResponse) -> Bool {
        if lhs.tx != rhs.tx {
            return false
        }
        if lhs.txResponse != rhs.txResponse {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(tx)
        hasher.combine(txResponse)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGetTxResponse: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GetTxResponse {
        return
            try GetTxResponse(
                tx: FfiConverterTypeTx.read(from: &buf), 
                txResponse: FfiConverterTypeTxResponse.read(from: &buf)
        )
    }

    public static func write(_ value: GetTxResponse, into buf: inout [UInt8]) {
        FfiConverterTypeTx.write(value.tx, into: &buf)
        FfiConverterTypeTxResponse.write(value.txResponse, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGetTxResponse_lift(_ buf: RustBuffer) throws -> GetTxResponse {
    return try FfiConverterTypeGetTxResponse.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGetTxResponse_lower(_ value: GetTxResponse) -> RustBuffer {
    return FfiConverterTypeGetTxResponse.lower(value)
}


/**
 * Configuration for the transaction.
 */
public struct TxConfig {
    /**
     * Custom gas limit for the transaction (in `utia`).
     */
    public var gasLimit: UInt64?
    /**
     * Custom gas price for fee calculation.
     */
    public var gasPrice: Double?
    /**
     * Memo for the transaction
     */
    public var memo: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Custom gas limit for the transaction (in `utia`).
         */gasLimit: UInt64?, 
        /**
         * Custom gas price for fee calculation.
         */gasPrice: Double?, 
        /**
         * Memo for the transaction
         */memo: String?) {
        self.gasLimit = gasLimit
        self.gasPrice = gasPrice
        self.memo = memo
    }
}

#if compiler(>=6)
extension TxConfig: Sendable {}
#endif


extension TxConfig: Equatable, Hashable {
    public static func ==(lhs: TxConfig, rhs: TxConfig) -> Bool {
        if lhs.gasLimit != rhs.gasLimit {
            return false
        }
        if lhs.gasPrice != rhs.gasPrice {
            return false
        }
        if lhs.memo != rhs.memo {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(gasLimit)
        hasher.combine(gasPrice)
        hasher.combine(memo)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTxConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TxConfig {
        return
            try TxConfig(
                gasLimit: FfiConverterOptionUInt64.read(from: &buf), 
                gasPrice: FfiConverterOptionDouble.read(from: &buf), 
                memo: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: TxConfig, into buf: inout [UInt8]) {
        FfiConverterOptionUInt64.write(value.gasLimit, into: &buf)
        FfiConverterOptionDouble.write(value.gasPrice, into: &buf)
        FfiConverterOptionString.write(value.memo, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTxConfig_lift(_ buf: RustBuffer) throws -> TxConfig {
    return try FfiConverterTypeTxConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTxConfig_lower(_ value: TxConfig) -> RustBuffer {
    return FfiConverterTypeTxConfig.lower(value)
}


/**
 * A result of correctly submitted transaction.
 */
public struct TxInfo {
    /**
     * Hash of the transaction.
     */
    public var hash: TendermintHash
    /**
     * Height at which transaction was submitted.
     */
    public var height: TendermintHeight

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Hash of the transaction.
         */hash: TendermintHash, 
        /**
         * Height at which transaction was submitted.
         */height: TendermintHeight) {
        self.hash = hash
        self.height = height
    }
}

#if compiler(>=6)
extension TxInfo: Sendable {}
#endif


extension TxInfo: Equatable, Hashable {
    public static func ==(lhs: TxInfo, rhs: TxInfo) -> Bool {
        if lhs.hash != rhs.hash {
            return false
        }
        if lhs.height != rhs.height {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(hash)
        hasher.combine(height)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTxInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TxInfo {
        return
            try TxInfo(
                hash: FfiConverterTypeTendermintHash.read(from: &buf), 
                height: FfiConverterTypeTendermintHeight.read(from: &buf)
        )
    }

    public static func write(_ value: TxInfo, into buf: inout [UInt8]) {
        FfiConverterTypeTendermintHash.write(value.hash, into: &buf)
        FfiConverterTypeTendermintHeight.write(value.height, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTxInfo_lift(_ buf: RustBuffer) throws -> TxInfo {
    return try FfiConverterTypeTxInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTxInfo_lower(_ value: TxInfo) -> RustBuffer {
    return FfiConverterTypeTxInfo.lower(value)
}


/**
 * Response to a tx status query
 */
public struct TxStatusResponse {
    /**
     * Height of the block in which the transaction was committed.
     */
    public var height: TendermintHeight
    /**
     * Index of the transaction in block.
     */
    public var index: UInt32
    /**
     * Execution_code is returned when the transaction has been committed
     * and returns whether it was successful or errored. A non zero
     * execution code indicates an error.
     */
    public var executionCode: ErrorCode
    /**
     * Error log, if transaction failed.
     */
    public var error: String
    /**
     * Status of the transaction.
     */
    public var status: TxStatus

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Height of the block in which the transaction was committed.
         */height: TendermintHeight, 
        /**
         * Index of the transaction in block.
         */index: UInt32, 
        /**
         * Execution_code is returned when the transaction has been committed
         * and returns whether it was successful or errored. A non zero
         * execution code indicates an error.
         */executionCode: ErrorCode, 
        /**
         * Error log, if transaction failed.
         */error: String, 
        /**
         * Status of the transaction.
         */status: TxStatus) {
        self.height = height
        self.index = index
        self.executionCode = executionCode
        self.error = error
        self.status = status
    }
}

#if compiler(>=6)
extension TxStatusResponse: Sendable {}
#endif


extension TxStatusResponse: Equatable, Hashable {
    public static func ==(lhs: TxStatusResponse, rhs: TxStatusResponse) -> Bool {
        if lhs.height != rhs.height {
            return false
        }
        if lhs.index != rhs.index {
            return false
        }
        if lhs.executionCode != rhs.executionCode {
            return false
        }
        if lhs.error != rhs.error {
            return false
        }
        if lhs.status != rhs.status {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(height)
        hasher.combine(index)
        hasher.combine(executionCode)
        hasher.combine(error)
        hasher.combine(status)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTxStatusResponse: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TxStatusResponse {
        return
            try TxStatusResponse(
                height: FfiConverterTypeTendermintHeight.read(from: &buf), 
                index: FfiConverterUInt32.read(from: &buf), 
                executionCode: FfiConverterTypeErrorCode.read(from: &buf), 
                error: FfiConverterString.read(from: &buf), 
                status: FfiConverterTypeTxStatus.read(from: &buf)
        )
    }

    public static func write(_ value: TxStatusResponse, into buf: inout [UInt8]) {
        FfiConverterTypeTendermintHeight.write(value.height, into: &buf)
        FfiConverterUInt32.write(value.index, into: &buf)
        FfiConverterTypeErrorCode.write(value.executionCode, into: &buf)
        FfiConverterString.write(value.error, into: &buf)
        FfiConverterTypeTxStatus.write(value.status, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTxStatusResponse_lift(_ buf: RustBuffer) throws -> TxStatusResponse {
    return try FfiConverterTypeTxStatusResponse.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTxStatusResponse_lower(_ value: TxStatusResponse) -> RustBuffer {
    return FfiConverterTypeTxStatusResponse.lower(value)
}


/**
 * Message signature
 */
public struct UniffiSignature {
    /**
     * signature bytes
     */
    public var bytes: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * signature bytes
         */bytes: Data) {
        self.bytes = bytes
    }
}

#if compiler(>=6)
extension UniffiSignature: Sendable {}
#endif


extension UniffiSignature: Equatable, Hashable {
    public static func ==(lhs: UniffiSignature, rhs: UniffiSignature) -> Bool {
        if lhs.bytes != rhs.bytes {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(bytes)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUniffiSignature: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UniffiSignature {
        return
            try UniffiSignature(
                bytes: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: UniffiSignature, into buf: inout [UInt8]) {
        FfiConverterData.write(value.bytes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUniffiSignature_lift(_ buf: RustBuffer) throws -> UniffiSignature {
    return try FfiConverterTypeUniffiSignature.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUniffiSignature_lower(_ value: UniffiSignature) -> RustBuffer {
    return FfiConverterTypeUniffiSignature.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Enum representing different types of account
 */

public enum Account {
    
    /**
     * Base account type
     */
    case base(BaseAccount
    )
    /**
     * Account for modules that holds coins on a pool
     */
    case module(ModuleAccount
    )
}


#if compiler(>=6)
extension Account: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAccount: FfiConverterRustBuffer {
    typealias SwiftType = Account

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Account {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .base(try FfiConverterTypeBaseAccount.read(from: &buf)
        )
        
        case 2: return .module(try FfiConverterTypeModuleAccount.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Account, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .base(v1):
            writeInt(&buf, Int32(1))
            FfiConverterTypeBaseAccount.write(v1, into: &buf)
            
        
        case let .module(v1):
            writeInt(&buf, Int32(2))
            FfiConverterTypeModuleAccount.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAccount_lift(_ buf: RustBuffer) throws -> Account {
    return try FfiConverterTypeAccount.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAccount_lower(_ value: Account) -> RustBuffer {
    return FfiConverterTypeAccount.lower(value)
}


extension Account: Equatable, Hashable {}







/**
 * Errors returned from [`GrpcClient`]
 */
public enum GrpcClientError: Swift.Error {

    
    
    /**
     * Error from grpc client
     */
    case GrpcError(
        /**
         * error message
         */msg: String
    )
    /**
     * Error during uniffi types conversion
     */
    case UniffiConversionError(
        /**
         * error message
         */msg: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGrpcClientError: FfiConverterRustBuffer {
    typealias SwiftType = GrpcClientError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GrpcClientError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .GrpcError(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 2: return .UniffiConversionError(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: GrpcClientError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .GrpcError(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .UniffiConversionError(msg):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGrpcClientError_lift(_ buf: RustBuffer) throws -> GrpcClientError {
    return try FfiConverterTypeGrpcClientError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGrpcClientError_lower(_ value: GrpcClientError) -> RustBuffer {
    return FfiConverterTypeGrpcClientError.lower(value)
}


extension GrpcClientError: Equatable, Hashable {}




extension GrpcClientError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}





/**
 * Errors returned from TxClient
 */
public enum TransactionClientError: Swift.Error {

    
    
    /**
     * Error returned from grpc
     */
    case GrpcError(
        /**
         * error message
         */msg: String
    )
    /**
     * Invalid account public key
     */
    case InvalidAccountPublicKey(
        /**
         * error message
         */msg: String
    )
    /**
     * Invalid account id
     */
    case InvalidAccountId(
        /**
         * error message
         */msg: String
    )
    /**
     * Error occured during signing
     */
    case SigningError(
        /**
         * error message
         */msg: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTransactionClientError: FfiConverterRustBuffer {
    typealias SwiftType = TransactionClientError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TransactionClientError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .GrpcError(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 2: return .InvalidAccountPublicKey(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 3: return .InvalidAccountId(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 4: return .SigningError(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TransactionClientError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .GrpcError(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .InvalidAccountPublicKey(msg):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .InvalidAccountId(msg):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .SigningError(msg):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTransactionClientError_lift(_ buf: RustBuffer) throws -> TransactionClientError {
    return try FfiConverterTypeTransactionClientError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTransactionClientError_lower(_ value: TransactionClientError) -> RustBuffer {
    return FfiConverterTypeTransactionClientError.lower(value)
}


extension TransactionClientError: Equatable, Hashable {}




extension TransactionClientError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Represents state of the transaction in the mempool
 */

public enum TxStatus {
    
    /**
     * The transaction is not known to the node, it could be never sent.
     */
    case unknown
    /**
     * The transaction is still pending.
     */
    case pending
    /**
     * The transaction was evicted from the mempool.
     */
    case evicted
    /**
     * The transaction was committed into the block.
     */
    case committed
}


#if compiler(>=6)
extension TxStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTxStatus: FfiConverterRustBuffer {
    typealias SwiftType = TxStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TxStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .unknown
        
        case 2: return .pending
        
        case 3: return .evicted
        
        case 4: return .committed
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TxStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .unknown:
            writeInt(&buf, Int32(1))
        
        
        case .pending:
            writeInt(&buf, Int32(2))
        
        
        case .evicted:
            writeInt(&buf, Int32(3))
        
        
        case .committed:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTxStatus_lift(_ buf: RustBuffer) throws -> TxStatus {
    return try FfiConverterTypeTxStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTxStatus_lower(_ value: TxStatus) -> RustBuffer {
    return FfiConverterTypeTxStatus.lower(value)
}


extension TxStatus: Equatable, Hashable {}






#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionDouble: FfiConverterRustBuffer {
    typealias SwiftType = Double?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDouble.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDouble.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeTxConfig: FfiConverterRustBuffer {
    typealias SwiftType = TxConfig?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeTxConfig.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeTxConfig.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeBlob: FfiConverterRustBuffer {
    typealias SwiftType = [Blob]

    public static func write(_ value: [Blob], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeBlob.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Blob] {
        let len: Int32 = try readInt(&buf)
        var seq = [Blob]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeBlob.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeCoin: FfiConverterRustBuffer {
    typealias SwiftType = [Coin]

    public static func write(_ value: [Coin], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCoin.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Coin] {
        let len: Int32 = try readInt(&buf)
        var seq = [Coin]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeCoin.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeAccount: FfiConverterRustBuffer {
    typealias SwiftType = [Account]

    public static func write(_ value: [Account], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeAccount.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Account] {
        let len: Int32 = try readInt(&buf)
        var seq = [Account]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeAccount.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_MAYBE_READY: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureCelestiaGrpcInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                uniffiFutureContinuationCallback,
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
private func uniffiTraitInterfaceCallAsync<T>(
    makeCall: @escaping () async throws -> T,
    handleSuccess: @escaping (T) -> (),
    handleError: @escaping (Int8, RustBuffer) -> ()
) -> UniffiForeignFuture {
    let task = Task {
        do {
            handleSuccess(try await makeCall())
        } catch {
            handleError(CALL_UNEXPECTED_ERROR, FfiConverterString.lower(String(describing: error)))
        }
    }
    let handle = UNIFFI_FOREIGN_FUTURE_HANDLE_MAP.insert(obj: task)
    return UniffiForeignFuture(handle: handle, free: uniffiForeignFutureFree)

}

private func uniffiTraitInterfaceCallAsyncWithError<T, E>(
    makeCall: @escaping () async throws -> T,
    handleSuccess: @escaping (T) -> (),
    handleError: @escaping (Int8, RustBuffer) -> (),
    lowerError: @escaping (E) -> RustBuffer
) -> UniffiForeignFuture {
    let task = Task {
        do {
            handleSuccess(try await makeCall())
        } catch let error as E {
            handleError(CALL_ERROR, lowerError(error))
        } catch {
            handleError(CALL_UNEXPECTED_ERROR, FfiConverterString.lower(String(describing: error)))
        }
    }
    let handle = UNIFFI_FOREIGN_FUTURE_HANDLE_MAP.insert(obj: task)
    return UniffiForeignFuture(handle: handle, free: uniffiForeignFutureFree)
}

// Borrow the callback handle map implementation to store foreign future handles
// TODO: consolidate the handle-map code (https://github.com/mozilla/uniffi-rs/pull/1823)
fileprivate let UNIFFI_FOREIGN_FUTURE_HANDLE_MAP = UniffiHandleMap<UniffiForeignFutureTask>()

// Protocol for tasks that handle foreign futures.
//
// Defining a protocol allows all tasks to be stored in the same handle map.  This can't be done
// with the task object itself, since has generic parameters.
fileprivate protocol UniffiForeignFutureTask {
    func cancel()
}

extension Task: UniffiForeignFutureTask {}

private func uniffiForeignFutureFree(handle: UInt64) {
    do {
        let task = try UNIFFI_FOREIGN_FUTURE_HANDLE_MAP.remove(handle: handle)
        // Set the cancellation flag on the task.  If it's still running, the code can check the
        // cancellation flag or call `Task.checkCancellation()`.  If the task has completed, this is
        // a no-op.
        task.cancel()
    } catch {
        print("uniffiForeignFutureFree: handle missing from handlemap")
    }
}

// For testing
public func uniffiForeignFutureHandleCountCelestiaGrpc() -> Int {
    UNIFFI_FOREIGN_FUTURE_HANDLE_MAP.count
}
public func parseBech32Address(bech32Address: String)throws  -> RustAddress  {
    return try  FfiConverterTypeRustAddress_lift(try rustCallWithError(FfiConverterTypeTransactionClientError_lift) {
    uniffi_celestia_grpc_fn_func_parse_bech32_address(
        FfiConverterString.lower(bech32Address),$0
    )
})
}
public func protoEncodeSignDoc(signDoc: SignDoc) -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_celestia_grpc_fn_func_proto_encode_sign_doc(
        FfiConverterTypeSignDoc_lower(signDoc),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_celestia_grpc_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_celestia_grpc_checksum_func_parse_bech32_address() != 5259) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_celestia_grpc_checksum_func_proto_encode_sign_doc() != 18886) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_celestia_grpc_checksum_method_grpcclient_broadcast_tx() != 49905) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_celestia_grpc_checksum_method_grpcclient_get_account() != 38846) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_celestia_grpc_checksum_method_grpcclient_get_accounts() != 48735) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_celestia_grpc_checksum_method_grpcclient_get_all_balances() != 24356) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_celestia_grpc_checksum_method_grpcclient_get_auth_params() != 51632) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_celestia_grpc_checksum_method_grpcclient_get_balance() != 9112) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_celestia_grpc_checksum_method_grpcclient_get_blob_params() != 15263) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_celestia_grpc_checksum_method_grpcclient_get_block_by_height() != 9330) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_celestia_grpc_checksum_method_grpcclient_get_latest_block() != 13069) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_celestia_grpc_checksum_method_grpcclient_get_min_gas_price() != 33600) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_celestia_grpc_checksum_method_grpcclient_get_spendable_balances() != 12163) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_celestia_grpc_checksum_method_grpcclient_get_total_supply() != 63802) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_celestia_grpc_checksum_method_grpcclient_get_tx() != 22739) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_celestia_grpc_checksum_method_grpcclient_simulate() != 3202) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_celestia_grpc_checksum_method_grpcclient_tx_status() != 30789) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_celestia_grpc_checksum_method_txclient_app_version() != 12249) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_celestia_grpc_checksum_method_txclient_last_seen_gas_price() != 24951) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_celestia_grpc_checksum_method_txclient_submit_blobs() != 57081) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_celestia_grpc_checksum_method_txclient_submit_message() != 49667) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_celestia_grpc_checksum_method_uniffisigner_sign() != 45956) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_celestia_grpc_checksum_constructor_grpcclient_create() != 12455) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_celestia_grpc_checksum_constructor_txclient_create() != 34913) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitUniffiSigner()
    uniffiEnsureCelestiaProtoInitialized()
    uniffiEnsureCelestiaTypesInitialized()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureCelestiaGrpcInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all