name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint files
        run: yarn lint

      - name: Typecheck files
        run: yarn typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run unit tests
        run: yarn test --maxWorkers=2 --coverage

  # build-library:
  #   needs: [lint, test, generate-lumina]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v4
  #
  #     - name: Setup
  #       uses: ./.github/actions/setup
  #
  #     - name: Build package
  #       run: yarn prepare
  #
  # publish-library:
  #   needs: [lint, test, generate-lumina, build-library]
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v4
  #
  #     - name: Setup
  #       uses: ./.github/actions/setup
  #
  #     - name: Setup Node.js for GitHub Packages
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '18.x'
  #         registry-url: 'https://npm.pkg.github.com'
  #         scope: '@leapwallet'
  #
  #     - name: Build package
  #       run: yarn prepare
  #
  #     - name: Publish to GitHub Packages
  #       run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
